targetBaseDir: D:\BaiduNetdiskWorkspace
sourceBaseDir: null
rule:
  - dirName: picture
    regular:
      - .*\.jpg$
      - .*\.png$
  - dirName: vedio
    regular:
      - .*\.mp4$
  - dirName: pdf
    regular:
      - .*\.pdf$
  - dirName: ppt
    regular:
      - .*\.pptx


excludeRules:
  - ^BaiduNetdiskWorkspace.*